### ISSUE TITLE
[Question] v50 status?

### ISSUE THREAD

**Issue by CatsArmy** [tonydimalta/LCSpawnOnPlayerFix#1] opened 2024-04-11 16:07 UTC
do you know if this bug been fixed in v50?
if it hasnt been fixed does the mod still work?

**Comment by tonydimalta** [comment] 2024-04-11 20:41
This issue hasn't been fixed in v50 but the version is still in public beta so I'll need to wait for the official release to be certain.
The mod should still work as it's not dependent on a specific moon or any changes from v50.

**Comment by tonydimalta** [comment] 2024-09-23 18:39
It still works, I can see my visualisation debug highlighting the nearby nodes and filter them out when spawning (night time / outside) enemies.
`[Debug  :LCSpawnOnPlayerFix] "RoundManagerPatch" Removed 7 spawn points too close to players`
Tested in v64 on Artifice
Note: If it's not working as intended, I'd suspect a conflict with another mod

**Closed as not planned** 2024-09-23 18:40 UTC
